version: "3.9"

x-general: &general
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_HOSTNAME: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: test_db

x-tomcat: &tomcat
  TOMCAT_USERNAME: tomcat
  TOMCAT_PASSWORD: tomcat
  TOMCAT_ALLOW_REMOTE_MANAGEMENT: "1"

x-mysql: &mysql
  MYSQL_ROOT_PASSWORD: root
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8

services:
  tomcat:
    image: bitnami/tomcat:9.0-debian-10
    ports:
      - '80:8080'
    volumes:
      - 'tomcat:/bitnami'
      - './docker/tomcat/data:/opt/bitnami/tomcat/webapps'
      - './api/RestAPI/target/RestAPI/:/opt/bitnami/tomcat/webapps/RestAPI/'
    environment:
      <<: *general
      <<: *tomcat
    container_name: "tomcat"
    cap_add: [NET_ADMIN]
    user: root

# Accessible outside the docker environment at localhost:3306
# Within the docker environment the database is accessible at mysql:3306
  mysql:
    #image: mysql:8.0.23
    build: ./docker/mysql/.
    restart: always
    environment:
      <<: *general
      <<: *mysql
    ports:
      - 3306:3306
    volumes:
      # on the left side of the semicolon is the directory in which Docker looks for init.sql
      - ./docker/mysql_data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

# Adminer visualises the data in the database. It is accessible in the browser at localhost:8888
  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8888:8080

volumes:
  tomcat:
  mysql_data:
